config/routes.rb
Rails.application.routes.draw do

  apipie

  root to: "public/teams#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #
  # devise_for :admins, path: 'admin/admins'
  devise_for :admins, :controllers => {
      sessions: "admin/admins/sessions",
      registrations: "admin/admins/registrations",
      passwords: "admin/admins/passwords"
  }

  devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: "public/users/passwords"
  }

  namespace :admin do
    resources :teams, except: :show do
      resources :players
      post '/import_csv', to: 'players#import_csv'
    end

    resources :current_passwords, only: [:new, :create]
    resources :admins
    resources :users, only: [:index, :destroy]
    resources :boards, only: [:index, :destroy] do
      resources :responses, only: [:index, :destroy]
    end
  end


  # API
  #
  # /api/v1/authでアクセス可能
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
          registrations: 'api/v1/auth/registrations'
      }
    end
  end

  namespace :api do
    namespace :v1 do
      resources :teams do
        resources :players, only: [:index, :show]
      end

      resources :boards, only: [:index, :create, :destroy] do
        resources :responses, only: [:index, :create, :destroy]
      end
    end
  end


  # scope module: :public do
  #   # 例resources :products # => /products
  # end
end

app/models/board.rb
class Board < ApplicationRecord

  # バリデーション
  validates :title, presence: true,
            length: { maximum: 30 }

  # アソシエーション
  has_many :responses, dependent: :destroy
  belongs_to :user


  # スコープ
  scope :search_title, ->(title) { where("title LIKE ?", "%#{title}%") }
  scope :search_title, ->(title) { where("title LIKE ?", "%#{title}%") }
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < Admin::ApplicationController

  def index
    @title_search   = params[:title_search]
    @comment_search = params[:comment_search]
    @user_search    = params[:user_search]

    @boards = Board.includes(:responses).includes(:user)

    if @title_search.present?
      @boards = @boards.search_title(@title_search)
    end

    if @comment_search.present?
      @boards = @boards.merge(Response.search_like_body(@comment_search)).references(:responses)
    end

    if @user_search.present?
      @boards = @boards.merge(User.search_like_users(@user_search)).references(:user)
    end

    if @title_search.blank? && @comment_search.blank? && @user_search.blank?
      @boards = @boards.all
    end

    @boards = @boards.page(params[:page]).per(30)
  end

  def destroy
    begin
      Board.find(params[:id]).destroy
    rescue => e
      flash[:danger] = e.message
      redirect_back(fallback_location: admin_boards_path) and return
    end
    flash[:success] = "スレッドを削除しました。"
    redirect_back(fallback_location: admin_boards_path) and return
  end
end

app/controllers/api/v1/boards_controller.rb
class Api::V1::BoardsController < Api::V1::ApplicationController

  api :GET, '/api/v1/boards?title=title_name', 'スレッド一覧を返します'
  # エラーの指定はこのような形で
  error code: 400
  error code: 401, desc: 'Unauthorized'
  error code: 404, desc: 'Not Found'

  # 利用例は example に記載
  example <<-EDOC
  ## Request
    ### Header 
    {
      Content-Type:application/json,
      access-token:jnvx5l-6EamupzK2BO7Jlg,
      client:27g9tBTLDVKEhmT5etvDdw,
      uid:test@test.com
    }
    ### Body 
    {}
  ## Response
  ### 正常系
  {
    "bords": [
      {
        "id": 1,
        "title": "Nectar in a Sieve",
        "user_id": 5,
        "created_at": "2018-11-27T00:19:26.000+09:00",
        "updated_at": "2018-11-27T00:19:26.000+09:00",
        "user": {
            "id": 5,
            "first_name": "颯",
            "last_name": "田村"
        }
      },
      {
        "id": 2,
        "title": "Jesting Pilate",
        "user_id": 5,
        "created_at": "2018-11-27T00:19:26.000+09:00",
        "updated_at": "2018-11-27T00:19:26.000+09:00",
        "user": {
            "id": 5,
            "first_name": "颯",
            "last_name": "田村"
        }
      },
      {
        "id": 3,
        "title": "The Way Through the Woods",
        "user_id": 5,
        "created_at": "2018-11-27T00:19:26.000+09:00",
        "updated_at": "2018-11-27T00:19:26.000+09:00",
        "user": {
            "id": 5,
            "first_name": "颯",
            "last_name": "田村"
        }
      }
    ],
    "meta": {
      "page": 1,
      "per_page": 32,
      "page_count": 32,
      "total_count": 95,
      "link": {
        "self": "http://localhost:3000/api/v1/boards?page=1",
        "first": "http://localhost:3000/api/v1/boards?page=1",
        "previous": null,
        "next": "http://localhost:3000/api/v1/boards?page=2",
        "last": "http://localhost:3000/api/v1/boards?page=32"
      }
    }
  }
  ### Error
    {
      "errors": [
        "ログインまたは登録が必要です。"
      ]
    }
  EDOC
  def index
    if params[:title].present?
      @boards = Board.search_title(params[:title]).page(params[:page]).per(30)
    else
      @boards = Board.all.page(params[:page]).per(30)
    end
    render 'index', formats: 'json', handlers: 'jbuilder'
  end


  api :POST, '/api/v1/boards', 'スレッドを登録します'
  # エラーの指定はこのような形で
  error code: 400, desc: 'title必須'
  error code: 400, desc: 'titleは30字以内'
  error code: 401, desc: 'Unauthorized'
  error code: 404, desc: 'Not Found'
  example <<-EDOC
  ## Request
  ### Header 
  {
    Content-Type:application/json,
    access-token:jnvx5l-6EamupzK2BO7Jlg,
    client:27g9tBTLDVKEhmT5etvDdw,
    uid:test@test.com
  }
  ### Body 
  {
    "board": {
      "title": "テスト"
    }
  }
  ## Response
  ### 正常系
  {
    "status": "success",
    "board": {
      "id": 96,
      "title": "テスト",
      "user_id": 6,
      "created_at": "2018-11-27T00:49:04.000+09:00",
      "updated_at": "2018-11-27T00:49:04.000+09:00",
      "user": {
        "id": 6,
        "first_name": "",
        "last_name": ""
      }
    }
  }
  ### Error(未ログイン)
    {
      "errors": [
        "ログインまたは登録が必要です。"
      ]
    }

  ### Error(パラメータ)
  {
    "code": "400",
    "status": "error",
    "data": {
      "board": {
        "title": null
      }
    },
    "errors": {
      "title": [
        "を入力してください"
      ],
      "full_messages": [
        "タイトルを入力してください"
      ]
    }
  }
  EDOC
  def create
    @board = current_user.boards.build(bord_params)
    @params = params
    if @board.save
      render 'create', formats: 'json', handlers: 'jbuilder'
    else
      render 'error', formats: 'json', handlers: 'jbuilder'
    end
  end

  api :DELETE, '/api/v1/boards/:id', 'スレッドを削除します。'
  error code: 400, desc: ':idは存在する'
  error code: 400, desc: '自作のスレッドのみ削除可能'
  error code: 401, desc: 'Unauthorized'
  error code: 404, desc: 'Not Found'
  example <<-EDOC
  ## Request
  ### Header 
  {
    Content-Type:application/json,
    access-token:jnvx5l-6EamupzK2BO7Jlg,
    client:27g9tBTLDVKEhmT5etvDdw,
    uid:test@test.com
  }
  ### Body 
  {}
  ## Response
  ### 正常系
  {
    "status": "success"
  }
  ### Error(未ログイン)
  {
    "errors": [
      "ログインまたは登録が必要です。"
    ]
  }

  ### Error(パラメータ1)
  {
    "code": "400",
    "errors": [
        "Couldn't find Board with 'id'=9911111"
    ]
  }
  ### Error(パラメータ2)
  {
    "code": "400",
    "errors": [
        "スレッドは作成者しか削除することはできません。"
    ]
  }
  EDOC
  def destroy
    begin
      @board = Board.find(params[:id])
      if current_user.id != @board.user.id
        render :json => {'code' => '400', 'errors' => ["スレッドは作成者しか削除することはできません。"]} and return
      end
      @board.destroy!
    rescue => e
      render :json => {'code' => '400', 'errors' => [e.message]} and return
    end

    render :json => {'status' => 'success'} and return
  end

  private
  def bord_params
    params.require(:board).permit(:title)
  end
end

app/helpers/admin/boards_helper.rb
module Admin::BoardsHelper
end

app/helpers/api/v1/boards_helper.rb
module Api::V1::BoardsHelper
end

app/views/admin/boards/index.html.erb
<h1>スレッド一覧</h1>
<div>
  <%= form_tag(admin_boards_path, method: :get) do %>
    <%= text_field_tag(:title_search, @title_search, class: "form-control", placeholder: 'スレッド名') %><br>
    <%= text_field_tag(:comment_search, @comment_search, class: "form-control", placeholder: 'コメント内容') %><br>
    <%= text_field_tag(:user_search, @user_search, class: "form-control", placeholder: '作成者(苗字・名前・ニックネーム・苗字 名前・メールアドレス)') %>
    <br>
    <%= submit_tag "検索", class: 'btn btn-success' %>
  <% end %>
</div>
<br><br><br>

<table class="table">
  <thead>
  <tr>
    <th>No.</th>
    <th>ID.</th>
    <th>スレッド名</th>
    <th>作成者ID</th>
    <th>作成者</th>
    <th>作成者<br>(ニックネーム)</th>
    <th>メールアドレス</th>
    <th>作成日時</th>
    <th>更新日時</th>
    <th>コメント一覧</th>
    <th>削除</th>
  </tr>
  </thead>
  <tbody>
  <% @boards.each_with_index do |board, i| %>
  <tr>
    <td><%= i + 1 %></td>
    <td><%= board.id %></td>
    <td><%= board.title %></td>
    <td><%= board.user.id %></td>
    <td><%= board.user.get_full_name %></td>
    <td><%= board.user.nickname %></td>
    <td><%= board.user.email %></td>
    <td><%= board.created_at.strftime('%Y年%m月%d日 %H:%M:%S') %></td>
    <td><%= board.updated_at.strftime('%Y年%m月%d日 %H:%M:%S') %></td>
    <td>
      <%= link_to "コメント一覧", admin_board_responses_path(board), class: "btn btn-success" %>
    </td>
    <td>
      <%= link_to "削除", admin_board_path(board), method: :delete, data: { confirm: "削除してよろしいでしょうか？" }, class: "btn btn-danger" %>
    </td>
  </tr>
  <% end %>


    <%# @users.each_with_index do |user, i| %>
<!--      <tr>-->
<!--        <td><%#= i + 1 %></td>-->
<!--        <td><%#= user.id %></td>-->
<!--        <td><%#= user.last_name %></td>-->
<!--        <td><%#= user.first_name %></td>-->
<!--        <td><%#= user.nickname %></td>-->
<!--        <td><%#= user.email %></td>-->
<!--        <td><%#= user.created_at.strftime('%Y年%m月%d日 %H:%M:%S') %></td>-->
<!--        <td><%#= user.updated_at.strftime('%Y年%m月%d日 %H:%M:%S') %></td>-->
<!--        <td>-->
          <%#= link_to "削除", admin_user_path(user), method: :delete, class: "btn btn-danger", data: {confirm: "削除してよろしいですか？"} %>
<!--        </td>-->
<!--      </tr>-->
    <%# end %>
  </tbody>
</table>
<!--Todo: スタイル調整-->
<div><%= paginate @boards %></div>