config/routes.rb
Rails.application.routes.draw do

  apipie

  root to: "public/teams#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #
  # devise_for :admins, path: 'admin/admins'
  devise_for :admins, :controllers => {
      sessions: "admin/admins/sessions",
      registrations: "admin/admins/registrations",
      passwords: "admin/admins/passwords"
  }

  devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: "public/users/passwords"
  }

  namespace :admin do
    resources :teams, except: :show do
      resources :players
      post '/import_csv', to: 'players#import_csv'
    end

    resources :current_passwords, only: [:new, :create]
    resources :admins
    resources :users, only: [:index, :destroy]
    resources :boards, only: [:index, :destroy] do
      resources :responses, only: [:index, :destroy]
    end
  end


  # API
  #
  # /api/v1/authでアクセス可能
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
          registrations: 'api/v1/auth/registrations'
      }
    end
  end

  namespace :api do
    namespace :v1 do
      resources :teams do
        resources :players, only: [:index, :show]
      end

      resources :boards, only: [:index, :create, :destroy] do
        resources :responses, only: [:index, :create, :destroy]
      end
    end
  end


  # scope module: :public do
  #   # 例resources :products # => /products
  # end
end

app/views/admin/admins/_form.html.erb
<% if @admin.errors.any? %>
  <ul>
    <% @admin.errors.full_messages.each do |msg| %>
      <li>
        <span style="color:red;"><%= msg %></span>
      </li>
    <% end %>
  </ul>
<% end %>
<%= form_for [:admin, @admin] do |f| %>
  <div class="form-group">
    <%= f.label :last_name, '苗字' %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :first_name, '名前' %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :role, '権限' %>
    <%= f.select :role, [["スーパー", 1], ["通常", 2]], {}, { 'class' =>'form-control'} %>
  </div>
  <% if is_new_request? %>
    <div class="form-group">
      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, '確認用パスワード' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  <% end %>
  <div><%= f.submit(button_name, class: 'btn btn-success') %></div>
<% end %>

app/views/admin/admins/edit.html.erb
<%= render 'form', button_name:'変更' %>

app/views/admin/admins/index.html.erb
<div>
  <%= form_tag(admin_admins_path(format: :csv), method: :get, id: "admin_search_form") do %>
    <%#= label_tag :名前 %>
    <%= text_field_tag(:search_word, @search_word, class: "form-control", placeholder: '苗字・名前・苗字 名前・メールアドレス') %>
    <br>
    <%#= submit_tag "検索", class: 'btn btn-success' %>
    <input type="submit" value="検索" class="btn btn-success" onclick="submitAction('/admin/admins')">
    <input type="submit" value="CSV" class="btn btn-info" onclick="submitAction('/admin/admins.csv')">
  <% end %>
</div>
<%#= link_to "csv出力",admin_admins_path(format: :csv) %>
<br><br>
<div><%= link_to '新規作成', new_admin_admin_path %></div>
<table class="table">
  <thead>
  <tr>
    <th>ID</th>
    <th>名前</th>
    <th>メールアドレス</th>
    <th>Role</th>
    <th>作成日時</th>
    <th>更新日時</th>
    <th>編集</th>
<!--    <th>削除</th>-->
  </tr>
  </thead>
  <tbody>
  <% @admins.each do |admin| %>
    <tr>
      <td><%= admin.id %></td>
      <td><%= admin.full_name %></td>
      <td><%= admin.email %></td>
      <td><%= admin.role %></td>
      <td><%= admin.created_at.strftime('%Y年%m月%d日 %H:%M:%S') %></td>
      <td><%= admin.updated_at.strftime('%Y年%m月%d日 %H:%M:%S') %></td>
      <td><%= link_to '変更', edit_admin_admin_path(admin), class: 'btn btn-success' %></td>
      <td>
        <% if current_admin != admin %>
          <%= link_to("削除", admin_admin_path(admin), method: :delete, data: {confirm: '削除してよろしいでしょうか？'}, class: 'btn btn-danger') %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<!--Todo: スタイル調整-->
<div><%= paginate @admins %></div>

app/views/admin/admins/new.html.erb
<%= render 'form', button_name:'登録' %>