config/routes.rb
Rails.application.routes.draw do

  apipie

  root to: "public/teams#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #
  # devise_for :admins, path: 'admin/admins'
  devise_for :admins, :controllers => {
      sessions: "admin/admins/sessions",
      registrations: "admin/admins/registrations",
      passwords: "admin/admins/passwords"
  }

  devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: "public/users/passwords"
  }

  namespace :admin do
    resources :teams, except: :show do
      resources :players
      post '/import_csv', to: 'players#import_csv'
    end

    resources :current_passwords, only: [:new, :create]
    resources :admins
    resources :users, only: [:index, :destroy]
    resources :boards, only: [:index, :destroy] do
      resources :responses, only: [:index, :destroy]
    end
  end


  # API
  #
  # /api/v1/authでアクセス可能
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
          registrations: 'api/v1/auth/registrations'
      }
    end
  end

  namespace :api do
    namespace :v1 do
      resources :teams do
        resources :players, only: [:index, :show]
      end

      resources :boards, only: [:index, :create, :destroy] do
        resources :responses, only: [:index, :create, :destroy]
      end
    end
  end


  # scope module: :public do
  #   # 例resources :products # => /products
  # end
end

app/models/team.rb
class Team < ApplicationRecord

  mount_uploader :main_image, Admin::Teams::MainImageUploader

  # アソシエーション
  has_many :players, :dependent => :destroy

  # スコープ
  scope :order_league, -> { order(:league) }

  # バリデーション
  validates :name, presence: { message: 'は必須です。' }
  validates :league, presence: { message: 'は必須です。' }
  validates :stadium, presence: { message: 'は必須です。' }
  validates :address, presence: { message: 'は必須です。' }

  def get_league_name
    self.league == '1' ? 'セントラル' : 'パフィシック'
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < Admin::ApplicationController

  before_action :get_team, only: [:edit, :update, :destroy]


  def index
    @teams = Team.all.order_league.page(params[:page]).per(12)
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new team_params
    if @team.save
      flash[:success] = '球団の登録に成功しました。'
      redirect_to admin_teams_path
    else
      flash.now[:danger] = '入力項目に不備があります。'
      render 'new'
    end
  end
  
  def edit
  end

  def update
    if @team.update team_params
      flash[:success] = '球団の変更に成功しました。'
      redirect_to admin_teams_path
    else
      flash.now[:danger] = '入力項目に不備があります。'
      render 'edit'
    end
  end

  def destroy
    @team.destroy
    flash[:success] = '球団の削除に成功しました。'
    redirect_to admin_teams_path
  end

  private
  def team_params
    params.require(:team).permit(
        :name,
        :stadium,
        :address,
        :league,
        :main_image,
        :remove_main_image
    )
  end

  def get_team
    @team = Team.find(params[:id])
  end
end

app/controllers/api/v1/teams_controller.rb
class Api::V1::TeamsController < Api::V1::ApplicationController

  api :GET, '/api/v1/teams', '球団一覧を返します'
  # エラーの指定はこのような形で
  # error code: 401, desc: 'Unauthorized'
  error code: 404, desc: 'Not Found'

  # 利用例は example に記載
  example <<-EDOC
  ## Request
    ### Header 
    {
      Content-Type:application/json,
      access-token:jnvx5l-6EamupzK2BO7Jlg,
      client:27g9tBTLDVKEhmT5etvDdw,
      uid:test@test.com
    }
    ### Body 
    {}
  ## Response
  ### 正常系
    {
      "teams": [
          {
              "id": 1,
              "name": "読売ジャイアンツ",
              "main_image": null,
              "stadium": "Zana Burgs",
              "address": "Apt. 121 6183 Leffler Trace, West Aurore, AL 77807-0884",
              "league": "1",
              "created_at": "2018-10-17T03:50:29.000+09:00",
              "updated_at": "2018-10-17T03:50:29.000+09:00"
          },
          {
              "id": 2,
              "name": "広島東洋カープ",
              "main_image": null,
              "stadium": "Miller Turnpike",
              "address": "80264 Treutel Glen, Heaneyport, PA 84539-3583",
              "league": "1",
              "created_at": "2018-10-17T03:50:29.000+09:00",
              "updated_at": "2018-10-17T03:50:29.000+09:00"
          },
          {
              "id": 3,
              "name": "阪神タイガース",
              "main_image": null,
              "stadium": "Sherlene Street",
              "address": "6326 Vernon Inlet, Wymantown, CA 18331-4227",
              "league": "1",
              "created_at": "2018-10-17T03:50:29.000+09:00",
              "updated_at": "2018-10-17T03:50:29.000+09:00"
          }
      ],
      "meta": {
          "page": 1,
          "per_page": 12,
          "page_count": 12,
          "total_count": 36,
          "link": {
              "self": "http://localhost:3000/api/v1/teams?page=1",
              "first": "http://localhost:3000/api/v1/teams?page=1",
              "previous": null,
              "next": "http://localhost:3000/api/v1/teams?page=2",
              "last": "http://localhost:3000/api/v1/teams?page=12"
          }
      }
    }
  ### Error
    {
      "errors": [
        "ログインまたは登録が必要です。"
      ]
    }
  EDOC
  def index
    @teams = Team.all.order_league.page(params[:page]).per(12)
    render 'index', formats: 'json', handlers: 'jbuilder'
  end



  api :GET, '/api/v1/teams/:id', '球団詳細を返します'
  # エラーの指定はこのような形で
  # error code: 401, desc: 'Unauthorized'
  error code: 404, desc: 'Not Found'

  # 利用例は example に記載
  example <<-EDOC
  $ curl http://localhost:3000/api/v1/teams/1
  ## Request
    ### Header 
    {
      Content-Type:application/json,
      access-token:jnvx5l-6EamupzK2BO7Jlg,
      client:27g9tBTLDVKEhmT5etvDdw,
      uid:test@test.com
    }
    ### Body 
    {}
  ## response
  ### 正常系
    {
      "id": 1,
      "name": "読売ジャイアンツ",
      "main_image": null,
      "stadium": "Zana Burgs",
      "address": "Apt. 121 6183 Leffler Trace, West Aurore, AL 77807-0884",
      "league": "1",
      "created_at": "2018-10-17T03:50:29.000+09:00",
      "updated_at": "2018-10-17T03:50:29.000+09:00"
    }
  ### Error
    {
      "errors": [
        "ログインまたは登録が必要です。"
      ]
    }
  EDOC
  def show
    @team = Team.find(params[:id])
    render 'show', formats: 'json', handlers: 'jbuilder'
  end
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/views/admin/teams/_form.html.erb
<% if @team.errors.any? %>
<ul>
  <% @team.errors.full_messages.each do |msg| %>
    <li>
      <span style="color:red;"><%= msg %></span>
    </li>
  <% end %>
</ul>
<% end %>
<%= form_for [:admin, @team] do |f| %>
  <div class="form-group">
    <%= f.label :name, '球団名' %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%=f.label :main_image,"球団画像" %>
    <div>
      <% if @team.main_image? %>
        <%= image_tag @team.main_image.url  %><br>
        <%= f.label :削除 %>
        <%= f.check_box :remove_main_image %>
      <% end %>
    </div>
    <%= f.file_field :main_image %>
  </div>

  <div class="form-group">
    <%= f.label :league, 'リーグ' %>
    <%= f.select :league, {'セントラル' => 1, 'パフィシック' => 2}, {}, { 'class' =>'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :stadium, 'スタジアム' %>
    <%= f.text_field :stadium, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address, '住所' %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div><%= f.submit(button_name, class: 'btn btn-success') %></div>

<% end %>

app/views/admin/teams/edit.html.erb
<%= render 'form', button_name:'変更' %>

app/views/admin/teams/index.html.erb
<div><%= link_to '新規作成', new_admin_team_path %></div>
<table class="table">
  <thead>
  <tr>
    <th>ID</th>
    <th>球団</th>
    <th>画像</th>
    <th>リーグ</th>
    <th>スタジアム</th>
    <th>住所</th>
    <th>選手一覧</th>
    <th>編集</th>
    <th>削除</th>
  </tr>
  </thead>
  <tbody>
  <% @teams.each do |team| %>
  <tr>
    <td><%= team.id %></td>
    <td><%= team.name %></td>
    <td><%= image_tag(team.main_image.thumb.url) if team.main_image? %></td>
    <td><%= team.get_league_name %></td>
    <td><%= team.stadium %></td>
    <td><%= team.address %></td>
    <td><%= link_to("選手一覧", admin_team_players_path(team), class: 'btn btn-success') %></td>
    <td><%= link_to("編集", edit_admin_team_path(team), class: 'btn btn-success') %></td>
    <td><%= link_to("削除", admin_team_path(team), method: :delete, data: {confirm: '削除してよろしいでしょうか？'}, class: 'btn btn-danger') %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<!--Todo: スタイル調整-->
<div><%= paginate @teams %></div>

app/views/admin/teams/new.html.erb
<%= render 'form', button_name:'登録' %>